ifneq (,$(filter doriot_dca,$(USEMODULE)))
	USEMODULE += gnrc_sock
	USEMODULE += gnrc_sock_udp
	USEMODULE += gnrc_icmpv6_echo
	USEMODULE += gnrc_ipv6_nib
	USEMODULE += gnrc_ipv6
	USEMODULE += schedstatistics
	USEMODULE += shell
	USEMODULE += shell_commands
	USEMODULE += ps
	USEMODULE += od
	USEMODULE += fmt
	USEMODULE += xtimer
	USEMODULE += saul_default
endif
