ifneq (,$(filter doriot_dca,$(USEMODULE)))
	USEMODULE += gnrc_netdev_default
	USEMODULE += auto_init_gnrc_netif
	USEMODULE += gnrc_ipv6_default
	USEMODULE += shell
	USEMODULE += shell_commands
	USEMODULE += ps
	USEMODULE += gcoap
	USEMODULE += od
	USEMODULE += fmt
endif
